-- Create market_intelligence table if it doesn't exist
CREATE TABLE IF NOT EXISTS market_intelligence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Enable row level security
ALTER TABLE market_intelligence ENABLE ROW LEVEL SECURITY;

-- Create policies
DROP POLICY IF EXISTS "Allow select for all users" ON market_intelligence;
CREATE POLICY "Allow select for all users"
  ON market_intelligence FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Allow insert for all users" ON market_intelligence;
CREATE POLICY "Allow insert for all users"
  ON market_intelligence FOR INSERT
  WITH CHECK (true);

-- Enable realtime
ALTER PUBLICATION supabase_realtime ADD TABLE market_intelligence;
